# Change the prefix key to Ctrl-a
# ref: https://github.com/tmux/tmux/wiki/FAQ#why-is-c-b-the-prefix-key-how-do-i-change-it
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Enable mouse support
set -g mouse on

# Make True Color work in tmux
set -g default-terminal "tmux-256color"
set -sg terminal-overrides ",*:RGB"

# Set status bar display time for messages
set -g display-time 2000

# Configure the catppuccin plugin
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_flags "icon"

# Load catppuccin theme
run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Automatically rename windows based on the current command and path
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_command}:#{pane_current_path}'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'catppuccin/tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
